### ISSUE TITLE
Research Spike: iOS Crash logging

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#142]
Select the crash logging system that is compatible with iOS

Timebox: 2 hours

**Comment by pacu** [comment]
Disclaimer: I poked a little bit the firebase filters and crashes for iOS popped up.  So it actually works at some level. 


We've found two interesting canditates to switching from Firebase. Kevin poked from colleagues of his who are working at big tech and they all complained about firebase/crashlytics and mentioned two tools: Sentry and Bugsnag

https://www.bugsnag.com/
https://sentry.io/

Both have interesting proposals and lousy free/lite tier plans unfortunately.

But they have interesting upsides:

- They are Open Source:
- Both have some degree of data regulation compliance 
- they are not google
- have integration with fastlane to upload debugging symbols/proguard map files to symbolicate crashes.

Bugsnag also has the ability of providing On Premise deployment, meaning that we could run our own endpoint if we wanted to. 


# Section for questions

It would be good to get ahold of some representative to have some demo or questions answered

How's their Swift and Swift UI support?
What's their minimum  deployment version?
(to sentry) is it possible to run this on premise?

**Comment by defuse** [comment]
Both bugsnag and sentry are pretty sane about what data they collect (at least not any worse than Firebase/crashlytics), and provide control over what's uploaded:

- https://docs.bugsnag.com/platforms/android/automatically-captured-data/ (details on what's contained in the stack traces are here: https://docs.bugsnag.com/platforms/javascript/react/customizing-error-reports/, and docs for filtering out event information are here: https://docs.bugsnag.com/platforms/go/other/customizing-error-reports/#modifying-report-information)
- https://docs.sentry.io/data-management/sensitive-data/

For internal use at ECC, I'm only really worried about keys/seeds getting uploaded by mistake, and it looks like neither will do that with default settings, so that's good. For production deployments, both provide ways of filtering out information from the events so that they can be made more private.
