### ISSUE TITLE
Application logs viewable by the user

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#153]
The application should log user activity to aid in debugging and performance assessment. These detailed logs should be available to the user and shareable.

Requirements:
- [ ] The user can request logs within the app
- [ ] The logs do not have to be viewable on device

**Comment by gmale** [comment]
Note: this was not pointed because we need a bit more research before it is workable.

@pacu will look into a reasonable approach for creating and sharing logs in iOS, which could be either a secure logging library that we create under zcash or a sqlite database of logs or rolling flat files. Whatever solution we choose should be light weight enough to just get this task accomplished for now.
