### ISSUE TITLE
User can't restore or create new app after deleting the app without nuking it first

### ISSUE THREAD

**Issue by pacu** [zcash/zcash-ios-wallet#232]
can Credentials can outlive app upon deletion. When reinstalled previous seed phrase and birthday might be already present from previous install. 

Reproducing steps

1. create new wallet
2. delete the app without nuking the wallet
3. reinstall the app
4. attempt to create a new wallet or restore one previously created

expected: user should either be able perform these actions or wallet should start syncing the existing credentials 

result: the user can't proceed to any action

**Comment by pacu** [comment]
@geffenz what should we do if there are credentials present but the app does not have any databases (they got deleted when the app was deleted)

**Comment by geffenz** [comment]
**Please define credentials.**

If you **mean apple ios** credentials, we should encounter the error and take them to a page where it tell them there are existing credentials (but no seed) so please nuke this install. It should have a nuke button and nothing else.

If you mean **seed**, it should tell them it located a seed and it could restore. If they say yes, a standard downloading parms/syncing onboarding. If they say no, it should delete that seed and give them the normal option of import/create new.

However, let's consult sekurty ( @zebambam  @defuse  ) about expected behavior. It is possible a deleted app needs to be taken AS the intent to delete the seed. In this case, if this were a commercial product I consider making the user validate it is their seed by entering the last word (or something). This would be to stop snatch and grab phone hackers. But it would also kill an interesting way to find cryptocurrency you forgot (as you wouldn't have the seed either).

**As this has a limited audience, I think straight recovery is better and less time wasting for testers.**

**Comment by braddmiller** [comment]
completed, shipping today
