### ISSUE TITLE
Research Spike: Bitrise CI/CD

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#254]
We would like to move to a more automated dev process. Let's try Bitrise, the output of this research spike is an outline of the steps from code merge to artifact installed on devices with estimated dev effort for each step.

Hours: 4 hours

**Comment by pacu** [comment]
I've set up the build job to do Build only for now.

There are a couple of caveats:
1. The standard build machines are slow. little cores, little rams
2. the environment does not have rust installed so, it needs to be installed during the job
3. the wallet still uses the params bundled in so they need to be downloaded on each build


for 1. a Bitrise Rep has offered us to test the elite rigs, so we will.

for 2 and 3 there are a few tricks that we can do, which is actually using a cache task on the bitrise workflows to cache brew casks and other heavy stuff like cocoapods so that builds take less time 

once we have the build running consistently I'll set other further tasks

**Comment by pacu** [comment]
Tickets
ZcashLightClientKit #274 and #275

**Comment by pacu** [comment]
this repo #255 and #256
